export const INPUT_NAME_FROM = 'INPUT_NAME_FROM';
export const INPUT_EMAIL_FROM = 'INPUT_EMAIL_FROM';
export const INPUT_NAME_TO = 'INPUT_NAME_TO';
export const INPUT_EMAIL_TO = 'INPUT_EMAIL_TO';
export const INPUT_TOPIC = 'INPUT_TOPIC';
export const INPUT_MESSAGE = 'INPUT_MESSAGE';
